name: My Second Workflow
on: workflow_dispatch
jobs:
  my-first-job:
   runs-on: ubuntu-latest
   steps:
    - name: Print welcom
      run: echo "Hello World"
    - name: End step
      run: echo "end step"
  
 
